### PR TITLE
Generic OAuth2 support [keycloak for example]

### PR DESCRIPTION
**Pull request by jdbranham**
I'm not sure of the guidelines on contributing, and the CLA link seems to be broke.  

If there's not already plans for a generic oauth2 solution, here's one I've tested with 7.4   

Also, made a few changes to the docker image to integrate better with kubernetes.   
There are examples on how to configure usage here -  
https://github.com/savantly-net/knowage-docker
  
The docker-compose file may not work because it's using a mock server, but I can confirm it's working well with keycloak.  
This PR may require changes, as I made some assumptions about namespaces and class names.

### CODE REVIEW

**Comment by davide-zerbetto** [comment]
Dear Jeremy
thanks for your contribution. We will evaluate it as soon as possible.
As you noticed, unfortunately CLAHub service is no more available.
We are thinking on substituting CLAHub with something else.
At the moment you can have a look at our CLA conditions:

https://github.com/KnowageLabs/Knowage-Server/blob/master/CLA.md

I'll be back to you next week
Thanks

**Comment by davide-zerbetto** [comment]
recheck

**Comment by davide-zerbetto** [comment]
Dear Jeremy
sorry for being late.
I'enabling CLA assitant lite in this repo to automate CLA signature and check process.
Most likely you will receive some emails that invite you to sign the CLA, I'm working to have this github action to work properly.
Sorry for any inconvenience.
Best regards
Davide

**Comment by davide-zerbetto** [comment]
recheck

**Comment by davide-zerbetto** [comment]
Dear Jeremy
I don't know why all tests succeeded even if you did not sign the CLA (I was expecting the CLA assitant lite test to fail)....
Anyhow, as the previous comment by github-actions bot says, if you agree with our CLA terms and conditions, you must sign it by writing "I have read the CLA Document and I hereby sign the CLA" as a comment of this pull request to start the evaluation process, otherwise I'm afraid but we cannot accept it.
Thanks

**Comment by jdbranham** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jdbranham** [comment]
Thank you @davide-zerbetto

**Comment by davide-zerbetto** [comment]
Dear @jdbranham 
we evaluated your contribution: having a generic Oauth2 security connector adds value to Knowage and the code is straightforward, so thank you very much!!!

Just a few questions before merging, just to clarify:

1. can I test it with using docker container as described in https://github.com/savantly-net/knowage-docker? are there predefined users?
2. OAuth2SecurityInfoProvider.getRoles method returns only a few hard-coded roles (admin, modeladmin, dev, user). Are roles meant to exist both on Keycloak and on Knowage (and therefore they must be defined on both systems)? I ask this because Knowage can delegate roles management to external IdMs, and I'm not sure this is the case;
3. in OAuth2SecurityServiceSupplier.createUserProfile method, information are get from JSON coming from Keycloak: some attribute names are retrieved by config (user id, user name), while others are hard-coded (email, roles). What about moving everything in config? with defaults in case config is missing;
4. we would like to merge your generic Oauth2 connector with our, do you see any technical obstacle in this?

Thank you very much
Davide

**Pull request merged**
