### PR TITLE
spanish translation and all languages only helper-messages.json

### PR DESCRIPTION
**Pull request by johnfelipe**

### CODE REVIEW

**Comment by johnfelipe** [comment]
In zanata Is possible upload Json files directly?

**Comment by Redjaw** [comment]
Unfortunately not in the translated languages :( .
Let me investigate further so I can open you a easier way to contribute also for other languages.

**Comment by johnfelipe** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/KnowageLabs/Knowage-Server/blob/master/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

how can sign?

**Comment by johnfelipe** [comment]
> Unfortunately not in the translated languages :( . Let me investigate further so I can open you a easier way to contribute also for other languages.

im working for italian transcription dear, but i have my own method, more quickly of zanata UI, pls give me method for send that files or upload

**Comment by Redjaw** [comment]
@johnfelipe you can sign the CLA just writing the quoted text in a comment, so the check will no longer fail and you will be set as contributor.

> _**I have read the CLA Document and I hereby sign the CLA**_

I temporary disabled Zanata for yours PRs, I will merge them directly and take care of the needed repository pushes.
Just be sure to use utf-8 encoding and avoid trailing spaces in translation values.

Thank you very much!

**Comment by johnfelipe** [comment]
> **CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/KnowageLabs/Knowage-Server/blob/master/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
>    - - -
>    ***I have read the CLA Document and I hereby sign the CLA***
>    - - -
>    <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

I have read the CLA Document and I hereby sign the CLA

**Comment by Redjaw** [comment]
recheck

**Comment by Redjaw** [comment]
Or you can avoid to quote the signing text, maybe the GitHub action cannot recognize It...

**Comment by johnfelipe** [comment]
i already have another language, then i pull into this PR and, what is next movement?

**Comment by Redjaw** [comment]
> i already have another language, then i pull into this PR and, what is next movement?

Hi, thank you very much, as you prefere.
Splitting different PR for different languages make it easier for our reviewers to accept the merge, but a single PR will just take more time.

**Comment by Redjaw** [comment]
recheck

**Pull request merged**
