### PR TITLE
Metadata management dev

### PR DESCRIPTION
**Pull request by BojanSovticEngIT**
Metadata management v1.0 with requested changes after peer review.
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by BojanSovticEngIT** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by BojanSovticEngIT** [comment]
recheck

**Comment by vstanojevic** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vstanojevic** [comment]
recheck

**Comment by Redjaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
