### PR TITLE
Configuration Management

### PR DESCRIPTION
**Pull request by dbulatovicx32**
Configuration Management v1.0 with request changes after peer review.

### CODE REVIEW

**Comment by dbulatovicx32** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dbulatovicx32** [comment]
recheck

**Comment by vstanojevic** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vstanojevic** [comment]
recheck

**Review by Redjaw — APPROVED** [review]
Approved after requested peer-review modifications have been fixed

**Comment by Redjaw** [comment]
recheck

**Comment by Redjaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
